services:
  postgres:
    image: postgres:latest
    container_name: flare_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - megebase_network

  neo4j:
    image: neo4j:latest
    container_name: flare_neo4j
    environment:
        - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "${NEO4J_BOLT_PORT}:7687"
      - "${NEO4J_HTTP_PORT}:7474"
    volumes:
      - neo4j_data:/data
    networks:
      - megebase_network

volumes:
  postgres_data:
  neo4j_data:

networks:
  megebase_network:
    external: true