services:
  postgres:
    image: postgres:latest
    container_name: flare_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - megebase_network

  neo4j:
    image: neo4j:latest
    container_name: flare_neo4j
    environment:
        - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "${NEO4J_BOLT_PORT}:7687"
      - "${NEO4J_HTTP_PORT}:7474"
    volumes:
      - neo4j_data:/data
    networks:
      - megebase_network

  mongo:
    image: mongo:latest
    container_name: flare_mongo
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
    networks:
      - megebase_network

  mongo-express:
    image: mongo-express
    container_name: flare_mongo_express
    ports:
      - "${ME_CONFIG_MONGODB_PORT}:8081"
    environment:
        ME_CONFIG_MONGODB_SERVER: flare_mongo
        ME_CONFIG_MONGODB_ENABLE_ADMIN: true
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
        ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
        ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    networks:
      - megebase_network
    depends_on:
      - mongo

volumes:
  postgres_data:
  neo4j_data:
  mongo_data:

networks:
  megebase_network:
    external: true